# 构建阶段
FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o consumer ./cmd/consumer

# 运行阶段
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/consumer .
EXPOSE 9090
CMD [ "./consumer" ]